server:
  port: 8080

crypto:
  # only used if in AWS env
  aes-key-secret-name: myapp/aes-key  # matches your Python service
  # only use for local dev (32 bytes)
  local-key-base64: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=

aws:
  region: us-east-1

spring:
  profiles:
    active: local